name: core
description: Common shared code for club angel.
version: 0.0.1
#homepage: https://www.example.com
#author: succorer <email@example.com>

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  redux: ^3.0.0
  xml: ^3.0.1
  intl: any
  http: ^0.12.0
  reselect: ^0.4.0
  key_value_store: ^1.0.0
  kt_dart: ^0.6.2
  cloud_firestore: ^0.12.9
  firebase_storage: ^3.0.5
  flutter_image_compress: ^0.6.3
  uuid: ^2.0.2
  multi_image_picker: ^4.3.6
  libphonenumber: ^1.0.0
  shared_preferences: ^0.5.3+4
  firebase_auth: ^0.14.0+2
  country_code_picker: ^1.1.5
  carousel_slider: ^1.3.0
  connectivity: ^0.4.3+2
  sliding_up_panel: ^0.3.4
  keyboard_avoider: ^0.1.2

dev_dependencies:
  test: ^1.3.0
  mockito: ^3.0.0
  intl_translation: 0.17.0
